### ISSUE TITLE
[Task]: Custom input error when sending a governance transaction

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1713]
## Description

Fix custom input error when sending a governance transaction
Described by: https://github.com/iotaledger/firefly/issues/5505

## Motivation

Error is thrown when voting output is sent.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
I believe it's caused by `get_voting_output()` because it just looks at the current unspent outputs and if we just sent a voting transaction that is still pending (or account not synced yet again), then it will use it again the next time we vote

We could check if the voting output is used in another transaction already, but then we would basically return the same error again

Syncing should fix it, but I don't think that should happen randomly somewhere in the voting function just because there is a pending transaction

Would returning the information if the voting output is currently used in a transaction be good for you?

**Comment by Tuditi** [comment]
If I sync the account before sending a voting transaction, I still get the same error. Maybe I don't understand it entirely, but once a  user voted, the error seems to appear consistently.

**Comment by Tuditi** [comment]
The error was on our side. Pushing the 'enter' button called the submit action twice when sending certain transactions, which resulted in the error described above.
